<?php

namespace DoctrineProxies\__CG__\PayFox\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class E_MangoPay_Client extends \PayFox\Entities\E_MangoPay_Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'name', 'registeredName', 'clientId', 'primaryThemeColour', 'primaryButtonColour', 'logo', 'techEmails', 'adminEmails', 'fraudEmails', 'billingEmails', 'platformCategorization', 'platformDescription', 'platformURL', 'headquartersAddress', 'taxNumber', 'companyReference'];
        }

        return ['__isInitialized__', 'name', 'registeredName', 'clientId', 'primaryThemeColour', 'primaryButtonColour', 'logo', 'techEmails', 'adminEmails', 'fraudEmails', 'billingEmails', 'platformCategorization', 'platformDescription', 'platformURL', 'headquartersAddress', 'taxNumber', 'companyReference'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (E_MangoPay_Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getClientId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientId', []);

        return parent::getClientId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientId($clientId): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientId', [$clientId]);

        parent::setClientId($clientId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisteredName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegisteredName', []);

        return parent::getRegisteredName();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegisteredName($registeredName): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegisteredName', [$registeredName]);

        parent::setRegisteredName($registeredName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryThemeColour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryThemeColour', []);

        return parent::getPrimaryThemeColour();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryThemeColour($primaryThemeColour): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimaryThemeColour', [$primaryThemeColour]);

        parent::setPrimaryThemeColour($primaryThemeColour);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimaryButtonColour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimaryButtonColour', []);

        return parent::getPrimaryButtonColour();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimaryButtonColour($primaryButtonColour): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimaryButtonColour', [$primaryButtonColour]);

        parent::setPrimaryButtonColour($primaryButtonColour);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTechEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTechEmails', []);

        return parent::getTechEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function setTechEmails($techEmails): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTechEmails', [$techEmails]);

        parent::setTechEmails($techEmails);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminEmails', []);

        return parent::getAdminEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminEmails($adminEmails): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminEmails', [$adminEmails]);

        parent::setAdminEmails($adminEmails);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraudEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraudEmails', []);

        return parent::getFraudEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraudEmails($fraudEmails): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraudEmails', [$fraudEmails]);

        parent::setFraudEmails($fraudEmails);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingEmails', []);

        return parent::getBillingEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingEmails($billingEmails): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingEmails', [$billingEmails]);

        parent::setBillingEmails($billingEmails);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlatformCategorization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlatformCategorization', []);

        return parent::getPlatformCategorization();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlatformCategorization($platformCategorization): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlatformCategorization', [$platformCategorization]);

        parent::setPlatformCategorization($platformCategorization);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlatformDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlatformDescription', []);

        return parent::getPlatformDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlatformDescription($platformDescription): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlatformDescription', [$platformDescription]);

        parent::setPlatformDescription($platformDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlatformURL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlatformURL', []);

        return parent::getPlatformURL();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlatformURL($platformURL): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlatformURL', [$platformURL]);

        parent::setPlatformURL($platformURL);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeadquartersAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeadquartersAddress', []);

        return parent::getHeadquartersAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeadquartersAddress($headquartersAddress): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeadquartersAddress', [$headquartersAddress]);

        parent::setHeadquartersAddress($headquartersAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxNumber', []);

        return parent::getTaxNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxNumber($taxNumber): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxNumber', [$taxNumber]);

        parent::setTaxNumber($taxNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyReference', []);

        return parent::getCompanyReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyReference($companyReference): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyReference', [$companyReference]);

        parent::setCompanyReference($companyReference);
    }

}
