<?php

namespace DoctrineProxies\__CG__\PayFox\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class E_MangoPay_Wallet extends \PayFox\Entities\E_MangoPay_Wallet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'nullableProperties', 'id', 'owners', 'balanceCurrency', 'balanceAmount', 'fundsType', 'description', 'currency'];
        }

        return ['__isInitialized__', 'nullableProperties', 'id', 'owners', 'balanceCurrency', 'balanceAmount', 'fundsType', 'description', 'currency'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (E_MangoPay_Wallet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNullableProperties(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNullableProperties', []);

        return parent::getNullableProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function setNullableProperties(array $nullableProperties): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNullableProperties', [$nullableProperties]);

        parent::setNullableProperties($nullableProperties);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwners(): \Doctrine\Common\Collections\ArrayCollection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwners', []);

        return parent::getOwners();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwners(\Doctrine\Common\Collections\ArrayCollection $owners): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwners', [$owners]);

        parent::setOwners($owners);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalanceCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalanceCurrency', []);

        return parent::getBalanceCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalanceCurrency($balanceCurrency): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalanceCurrency', [$balanceCurrency]);

        parent::setBalanceCurrency($balanceCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalanceAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalanceAmount', []);

        return parent::getBalanceAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalanceAmount($balanceAmount): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalanceAmount', [$balanceAmount]);

        parent::setBalanceAmount($balanceAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getFundsType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFundsType', []);

        return parent::getFundsType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFundsType($fundsType): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFundsType', [$fundsType]);

        parent::setFundsType($fundsType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function update($params)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', [$params]);

        return parent::update($params);
    }

}
